# WIP
# version: '2'

# services:
#   backend:
#     build:
#       context: ./
#       dockerfile: ./backend/Dockerfile
#     command: npm run start:dev
#     tty: true
#     ports:
#       - "3500:3030"

#   frontend:
#     build:
#       context: ./
#       dockerfile: ./frontend/Dockerfile
#     command: npm run dev
#     tty: true
#     ports:
#       - "3600:3000"
